### ISSUE TITLE
Feature: weather_by_ids

### ISSUE THREAD

**Issue by FailSafe86** [csparpa/pyowm#112]
there is only one method in the owm25 file to retrieve a weather object from one city ID,

would it be useful to have a method that can take a list of ids. There is an api call that we can link to directly.

> http://api.openweathermap.org/data/2.5/group?id=524901,703448,2643743&units=metric

**Comment by csparpa** [comment]
Thanks @FailSafe86 you're right 
Would you like to contribute in this new feature?

**Comment by FailSafe86** [comment]
sure, would be glad too :+1:

**Comment by csparpa** [comment]
@FailSafe86 thanks, waiting for your feedback and code about it :)

**Comment by csparpa** [comment]
Added method with PR #123, closing
