### ISSUE TITLE
weather.py fails when forecast has a wind response by no value (NoneType has no copy fcn)

### ISSUE THREAD

**Issue by chfiii** [csparpa/pyowm#113]
At line 462 in weather.py:
    if 'wind' in d:
        wind = d['wind'].copy()    <---fails

Fix:

if 'wind' in d:
    if d['wind'] is None:
        wind = dict(speed=0)
    else:
        wind = d['wind'].copy()

Same code should go into the d['alst'['wind'] branch

**Comment by chfiii** [comment]
Found a fix in the develop branch.  It fixes the base case (d['wind']) but does not test the d['last']['wind'] case.  Suggest that the same test for d['last']['wind] is not None put there.

**Comment by csparpa** [comment]
Closing this as it duplicates an existing issue, will reopen that one
