### ISSUE TITLE
Reason: HTTP Error 401: Unauthorized Caused by: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by Harish515** [csparpa/pyowm#117]
Getting this exception while using a method 
observation = owm.weather_history_at_place('London,uk',start = now-onehour,end=now+fivedays)

APICallError: Exception in calling OWM web API.
Reason: HTTP Error 401: Unauthorized
Caused by: HTTP Error 401: Unauthorized
127.0.0.1 - - [04/Aug/2016 13:45:20] "POST / HTTP/1.1" 500 -

My code:
import pyowm
import pdb
from pyowm import timeutils
import datetime
now = datetime.datetime.now()
fivedays = datetime.timedelta(days=5)
onehour = datetime.timedelta(days=1)

owm = pyowm.OWM('my key')  # You MUST provide a valid API key

# Search for current weather in London (UK)
observation = owm.weather_history_at_place('London,uk',start = now-onehour,end=now+fivedays)
print observation

**Comment by csparpa** [comment]
@Harish515 the reason you get a 401 is because historical weather data is only available to premium OWM subscribers:

http://openweathermap.org/price
