### ISSUE TITLE
Rainfall variable not working in pyowm

### ISSUE THREAD

**Issue by kinoni** [csparpa/pyowm#119]
I am working on a mini project using python and scratch to get the weather details of any city using pyowm. 

All the variables are working except the rainfall. This variable always displays 0.0 value for any given city. 

Please let me know if this is a know issue or if there is any workaround. I am using the following API key:
cb6e0d582ffa76dde399d7a997021d69

Thanks

**Comment by csparpa** [comment]
Hello @kinoni thanks for reporting, can you please paste here an example of the actual code that you ran and is not working as you expected? Thanks a lot

**Comment by kinoni** [comment]
Hi,
Here is the python code:
import pyowm
import scratch
s = scratch.Scratch()


def listen():
    while True:
        try:
            yield s.receive()
        except scratch.ScratchError:
            raise StopIteration

for msg in listen():
    if 'key' in msg['sensor-update']:
        key = msg['sensor-update']['key']
        owm = pyowm.OWM(key)
    if 'location' in msg['sensor-update']:
        location = msg['sensor-update']['location']
        observation = owm.weather_at_place(location)
        w = observation.get_weather()
        temperature = w.get_temperature()['temp']
        rain = w.get_rain()
        if '1h' in rain:
            rainfall = rain['1h']
        else:
            rainfall = 0
        wind = w.get_wind()
        if 'speed'in wind:
            wind_speed = wind['speed']
        else:
            wind_speed = 0
        if 'deg' in wind:
            wind_direction = wind['deg']
        else:
            wind_direction = 0
        clouds = w.get_clouds()
        s.sensorupdate({'temperature': temperature - 273})
        s.sensorupdate({'rainfall': rainfall})
        s.sensorupdate({'wind_speed': wind_speed})
        s.sensorupdate({'wind_direction': wind_direction})
        s.sensorupdate({'clouds': clouds})

Please help me.

**Comment by csparpa** [comment]
This bit:

```
rain = w.get_rain()
if '1h' in rain:
  rainfall = rain['1h']
else:
  rainfall = 0
```

is wrong, as rain volumes are given by OWM based on the last 3 hours.

So you should call: `rainfall = rain['3h']` instead.

If you're quick enough, you can test it on Osaka (JP), it's raining over there right now...

**Comment by kinoni** [comment]
Wow.. that was super quick! Thanks

I will try that and get back to you.

**Comment by csparpa** [comment]
:) Good, no problems!

**Comment by kinoni** [comment]
Works perfectly! thanks again.
