### ISSUE TITLE
Release 2.4.0 - pyowm not working 

### ISSUE THREAD

**Issue by G10DRAS** [csparpa/pyowm#126]
I tried a simple python example with both Release 2.4.0 and 2.3.2.
2.3.2 is working as expected but 2.4.0 breaks and return some thing.

```
import pyowm
owm = pyowm.OWM('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
forecast = owm.daily_forecast("Milan,it")
fore = forecast.get_forecast()
print fore.to_JSON()
```
Release 2.3.2 return (Looks good)
`
{"reception_time": 1473901192, "interval": "daily", "Location": {"country": "IT", "name": "Milan", "coordinates": {"lat": 45.464161, "lon": 9.19199}, "ID": 6542283}, "weathers": [{"status": "Rain", "visibility_distance": null, "humidity": 0, "clouds": 6, "temperature": {"min": 290.02, "max": 300.84, "eve": 296.41, "morn": 290.87, "night": 290.02, "day": 300.84}, "dewpoint": null, "snow": {}, "detailed_status": "light rain", "reference_time": 1473850800, "weather_code": 500, "humidex": null, "rain": {"all": 0.6}, "sunset_time": 0, "pressure": {"press": 992.52, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 1.8}}, {"status": "Rain", "visibility_distance": null, "humidity": 95, "clouds": 36, "temperature": {"min": 287.88, "max": 294.37, "eve": 291.08, "morn": 293.09, "night": 287.88, "day": 294.1}, "dewpoint": null, "snow": {}, "detailed_status": "heavy intensity rain", "reference_time": 1473937200, "weather_code": 502, "humidex": null, "rain": {"all": 17.06}, "sunset_time": 0, "pressure": {"press": 1004.37, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 3.21}}, {"status": "Rain", "visibility_distance": null, "humidity": 85, "clouds": 48, "temperature": {"min": 286.26, "max": 294.7, "eve": 289.32, "morn": 286.26, "night": 286.84, "day": 294.7}, "dewpoint": null, "snow": {}, "detailed_status": "moderate rain", "reference_time": 1474023600, "weather_code": 501, "humidex": null, "rain": {"all": 3.07}, "sunset_time": 0, "pressure": {"press": 1005.58, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 2.11}}, {"status": "Rain", "visibility_distance": null, "humidity": 86, "clouds": 76, "temperature": {"min": 285.1, "max": 294.04, "eve": 290.78, "morn": 285.1, "night": 287.09, "day": 293.82}, "dewpoint": null, "snow": {}, "detailed_status": "moderate rain", "reference_time": 1474110000, "weather_code": 501, "humidex": null, "rain": {"all": 4.57}, "sunset_time": 0, "pressure": {"press": 1002.69, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 1.76}}, {"status": "Rain", "visibility_distance": null, "humidity": 0, "clouds": 28, "temperature": {"min": 285.98, "max": 294.75, "eve": 291.71, "morn": 286.97, "night": 285.98, "day": 294.75}, "dewpoint": null, "snow": {}, "detailed_status": "light rain", "reference_time": 1474196400, "weather_code": 500, "humidex": null, "rain": {"all": 1.78}, "sunset_time": 0, "pressure": {"press": 993.39, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 0.82}}, {"status": "Clear", "visibility_distance": null, "humidity": 0, "clouds": 0, "temperature": {"min": 284.76, "max": 296.22, "eve": 291.83, "morn": 284.76, "night": 286.09, "day": 296.22}, "dewpoint": null, "snow": {}, "detailed_status": "clear sky", "reference_time": 1474282800, "weather_code": 800, "humidex": null, "rain": {}, "sunset_time": 0, "pressure": {"press": 993.77, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "01d", "wind": {"speed": 0.79}}, {"status": "Rain", "visibility_distance": null, "humidity": 0, "clouds": 10, "temperature": {"min": 285.33, "max": 296.13, "eve": 291.88, "morn": 285.33, "night": 286.13, "day": 296.13}, "dewpoint": null, "snow": {}, "detailed_status": "light rain", "reference_time": 1474369200, "weather_code": 500, "humidex": null, "rain": {"all": 0.27}, "sunset_time": 0, "pressure": {"press": 994.13, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 1.09}}]}`

while Release 2.4.0 returns (bad data)
`
{"reception_time": 1473901093, "interval": "daily", "Location": {"country": "IT", "name": "None", "coordinates": {"lat": 44.93314, "lon": 7.54012}, "ID": 3172215}, "weathers": [{"status": "Rain", "visibility_distance": null, "humidity": 0, "clouds": 2, "temperature": {"min": 286.97, "max": 299.74, "eve": 293.66, "morn": 288.42, "night": 286.97, "day": 299.74}, "dewpoint": null, "snow": {}, "detailed_status": "light rain", "reference_time": 1473850800, "weather_code": 500, "humidex": null, "rain": {"all": 1.68}, "sunset_time": 0, "pressure": {"press": 960.7, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 1.72}}, {"status": "Rain", "visibility_distance": null, "humidity": 98, "clouds": 80, "temperature": {"min": 288.43, "max": 292.88, "eve": 288.93, "morn": 290.79, "night": 288.43, "day": 292.88}, "dewpoint": null, "snow": {}, "detailed_status": "heavy intensity rain", "reference_time": 1473937200, "weather_code": 502, "humidex": null, "rain": {"all": 41.63}, "sunset_time": 0, "pressure": {"press": 996.75, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 2.21}}, {"status": "Rain", "visibility_distance": null, "humidity": 92, "clouds": 64, "temperature": {"min": 283.94, "max": 292.1, "eve": 289.82, "morn": 288.36, "night": 283.94, "day": 292.1}, "dewpoint": null, "snow": {}, "detailed_status": "light rain", "reference_time": 1474023600, "weather_code": 500, "humidex": null, "rain": {"all": 1.88}, "sunset_time": 0, "pressure": {"press": 998.85, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 2.06}}, {"status": "Rain", "visibility_distance": null, "humidity": 76, "clouds": 32, "temperature": {"min": 283, "max": 294.69, "eve": 289.63, "morn": 283, "night": 286.74, "day": 292.97}, "dewpoint": null, "snow": {}, "detailed_status": "light rain", "reference_time": 1474110000, "weather_code": 500, "humidex": null, "rain": {"all": 0.43}, "sunset_time": 0, "pressure": {"press": 995.72, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 1.31}}, {"status": "Rain", "visibility_distance": null, "humidity": 0, "clouds": 5, "temperature": {"min": 283.28, "max": 294.1, "eve": 289.41, "morn": 283.52, "night": 283.28, "day": 294.1}, "dewpoint": null, "snow": {}, "detailed_status": "light rain", "reference_time": 1474196400, "weather_code": 500, "humidex": null, "rain": {"all": 1.56}, "sunset_time": 0, "pressure": {"press": 961.38, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 1.54}}, {"status": "Clear", "visibility_distance": null, "humidity": 0, "clouds": 0, "temperature": {"min": 282.46, "max": 295.32, "eve": 290.43, "morn": 282.46, "night": 284.19, "day": 295.32}, "dewpoint": null, "snow": {}, "detailed_status": "clear sky", "reference_time": 1474282800, "weather_code": 800, "humidex": null, "rain": {}, "sunset_time": 0, "pressure": {"press": 961.96, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "01d", "wind": {"speed": 1.47}}, {"status": "Rain", "visibility_distance": null, "humidity": 0, "clouds": 16, "temperature": {"min": 283.18, "max": 294.53, "eve": 290.23, "morn": 283.18, "night": 284.43, "day": 294.53}, "dewpoint": null, "snow": {}, "detailed_status": "light rain", "reference_time": 1474369200, "weather_code": 500, "humidex": null, "rain": {"all": 0.81}, "sunset_time": 0, "pressure": {"press": 962.11, "sea_level": null}, "sunrise_time": 0, "heat_index": null, "weather_icon_name": "10d", "wind": {"speed": 1.58}}]}`

see Location and weathers in JSON.
Even I try with different City, but result always the same.

```
forecast = owm.daily_forecast("Tokyo,jp")
forecast = owm.daily_forecast("London,uk")
```

**Comment by csparpa** [comment]
Hello, thanks for reporting this.
What python version are you using? Are you on a free or paid tier?

**Comment by G10DRAS** [comment]
python 2.7.3 and I am one free tier.

**Comment by csparpa** [comment]
@G10DRAS Please, I need you to be more precise in order to debug this issue properly.

What is not as expected in the 2.4.0 response?

I checked out the JSON and the only weird thing looks like the Location name, which is `"None"`
... what am I missing more?
Thanks

**Comment by csparpa** [comment]
I found out and fixed the problem on the Location name: it was caused by a bug in the code that turns the place names to UTF-8

@G10DRAS If you spot more unconsistencies please notify them

**Comment by G10DRAS** [comment]
Hello @csparpa thanks for quick fix. 

When I tested 3.4.0 yesterday, apart from Location name `None`, I saw json data return by api is always the same, no matter what ` city,country ` was passed to api. 

I will test the fix and let you know if I see more discrepancies.

**Comment by csparpa** [comment]
Good, thanks @G10DRAS

The fix is on a branch called 126_unicode_names, I will soon merge it to develop

**Comment by G10DRAS** [comment]
@csparpa, fix looks good so far.  thanks.

**Comment by csparpa** [comment]
cool 👍
