### ISSUE TITLE
'Location' object has no attribute 'get_id'

### ISSUE THREAD

**Issue by lardconcepts** [csparpa/pyowm#132]
For:

```
location = "Hampshire,uk"
obs = owm.weather_at_place(location)
l = obs.get_location()
name = l.get_name()
print(name)
regID = l.get_id()
print(regID)
```

I get:

```
Hampshire

Traceback (most recent call last):
  File "owtest.py", line 39, in <module>
    regID = l.get_id()
AttributeError: 'Location' object has no attribute 'get_id'
```

Using PyOWM 2.4.0 on current version of Python (3.5 at time of writing)
Apart from that (, it works fine, it just means I can't retrieve the ID.

**Comment by csparpa** [comment]
@lardconcepts I think it's your mistake here
I've tested your exact code, please notice the uppercase in the very last call:

```
regID = l.get_ID()
2647554
```

**Comment by lardconcepts** [comment]
Oh, silly me. Should'a copied and pasted. Thanks and sorry,

**Comment by csparpa** [comment]
No problems man ;) glad you like the library!
