### ISSUE TITLE
owm stop working

### ISSUE THREAD

**Issue by BlackSailor** [csparpa/pyowm#145]
Sorry, looking for a quick fix but don't know where to ask. After a year of work without problem it stop now. Trackback refer to this line in my code:
```obs = owm.weather_at_id(<my_id>)```

and

```
  File "/.../.../pyowm/webapi25/weather.py", line 430, in weather_from_dictionary
    if 'distance' in d['visibility']:
TypeError: argument of type 'int' is not iterable
```

**Comment by csparpa** [comment]
@BlackSailor thanks for reporting, can you tell me what version are you using? The latest one (2.5) ?

**Comment by csparpa** [comment]
@BlackSailor I tested out the call using PyOWM 2.5.0 and on city id `1704793` (Maanas, PH) and I get no errors.

Now, it looks like your error is generated by your *specific* city id... can you provide this please?

**Comment by BlackSailor** [comment]
Sorry for delay
```PYOWM_VERSION = '2.2.0'
LATEST_OWM_API_VERSION = '2.5'```

city = 3204793

**Comment by csparpa** [comment]
@BlackSailor good, thanks :) we have had this issue before (https://github.com/csparpa/pyowm/issues/76) so that's why I suggested to update
