### ISSUE TITLE
Doc or code error? Comma in locations search breaks things depending on number of results

### ISSUE THREAD

**Issue by lardconcepts** [csparpa/pyowm#146]
Given the following for a town I know there is **only one of** in the UK:

```
location = "Llandinam,UK"
mobs = owm.weather_at_places(location,searchtype='accurate',limit=3)
for mob in mobs:
    l = mob.get_location()
    print(l.get_name(),l.get_country()) 
```

The result is either:

```
Oldmill GB
Glassel GB
Baulds GB
```

or (and this might be a flakey API this morning)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyowm/commons/weather_client.py", line 58, in _lookup_cache_or_invoke_API
    response = urlopen(API_full_url, None, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getweather.py", line 46, in <module>
    mobs = owm.weather_at_places(location,searchtype='accurate',limit=3)
  File "/usr/local/lib/python3.5/dist-packages/pyowm/webapi25/owm25.py", line 316, in weather_at_places
    json_data = self._api.call_API(FIND_OBSERVATIONS_URL, params)
  File "/usr/local/lib/python3.5/dist-packages/pyowm/commons/weather_client.py", line 91, in call_API
    return self._lookup_cache_or_invoke_API(self._cache, url, timeout)
  File "/usr/local/lib/python3.5/dist-packages/pyowm/commons/weather_client.py", line 64, in _lookup_cache_or_invoke_API
    raise api_call_error.APICallError(str(e), e)
pyowm.exceptions.api_call_error.APICallError: <exception str() failed>
```

Given "Llandinam UK" (no comma), it returns: ```Llandinam United Kingdom```

But where there is **more** than one town, if I put: "Gillingham UK" it returns ```Gillingham United Kingdom``` but if I put "Gillingham,UK"  it returns 
```
Gillingham GB
Gillingham GB
```

In other words, I cannot seem to find a way of handling results properly while narrowing to a particular country.

**Comment by csparpa** [comment]
Hi @lardconcepts I tried to reproduce your calls and I get results similar to yours (`Llandinam,UK` gives me back 11 matching items!)

This behaviour is not caused by PyOWM, it's caused by the way the API internals work. I frankly have no idea what goes on behind the scenes whenever somebody looks up data using country _names_ as a query key: I guess - but I may be wrong - that they're doing some kind of exact text matching against the locality names listed on their datastores. That's probably the reason why putting a comma or not is causing different data to be returned.

But fear not! The API mainatiners themselves admit their system is giving back some ambiguous data in some cases (like your one) and therefore [warn us to use city IDs instead of city names](https://openweathermap.org/current):

> Call API by city ID instead of city name, city coordinates or zip code. In this case you get precise respond exactly for your city. 

So here the best practice is to **avoid calling the API using strings to identify locations and use city IDs instead**

**Comment by lardconcepts** [comment]
Thanks for the explanation, but remember, I am not using not _location_ but _location**s**_  so ID is not possible.

In the end I just wrote something to loop through and then use a third party API to return a town based on postcode. Pasting here in case it's useful to anyone (sorry about the code - I don't do Python that much!)

```
def wsearch(location):
    resultlist = []
    search = owm.weather_at_places(location,searchtype='accurate')
    for results in search:
        l = results.get_location()
        country = l.get_country()
        name = l.get_name()
        if country == "GB" or country == "United Kingdom":
            lat = str(l.get_lat())
            lon = str(l.get_lon())
            ID = str(l.get_ID())
            data = requests.get("http://api.postcodes.io/postcodes?lon=" + lon + "&lat=" + lat + "&radius=1000")
            resp = data.json()
            county = resp['result'][0]['admin_county']
            if county == None:
                county = resp['result'][0]['admin_district']
            country = resp['result'][0]['country']
            names = name+"-"+county+"-"+country
            resultlist.append(ID+":"+names)
    return resultlist

```
