### ISSUE TITLE
Best way of getting county from multiple locations results?

### ISSUE THREAD

**Issue by lardconcepts** [csparpa/pyowm#147]
When locations search returns multiple town name results, even on the OWM website their seems to be no way of distinguishing which is which as no county name is given.

The only thing I can think of is to then pass the co-ords to http://postcodes.io/outcodes?lon=-3.3&lat=52.52 and get the county from that. 

Am I missing a trick here, or is this the only way? Thanks

**Comment by csparpa** [comment]
Hi @lardconcepts yes I think there is no other way of telling among search results having the same name other than using their lat/lon.

Please just notice that PyOWM is not "processing" data returned by the API in any way, so what you get from the PyOWM object model is basically what the API returned, only informations are organized a little bit better
