### ISSUE TITLE
Small typo in error message

### ISSUE THREAD

**Issue by pirateofitaly** [csparpa/pyowm#149]
Says "espressed" instead of "expressed."
very minor, just thought I'd pass it along. Thanks for the great  piece of software!

`File "/usr/local/lib/python2.7/site-packages/pyowm/webapi25/forecaster.py", line 404, in get_weather_at
    timeformatutils.to_UNIXtime(timeobject))`
 `File "/usr/local/lib/python2.7/site-packages/pyowm/utils/timeformatutils.py", line 132, in to_UNIXtime
    raise TypeError('The time value must be espressed either by an int ' `
`TypeError: The time value must be espressed either by an int UNIX time, a datetime.datetime object or an ISO8601-formatted string`

**Comment by csparpa** [comment]
Fixed with commit 0cb42ecc700a1386e30ba6d3d607a56b4bcda621
