### ISSUE TITLE
PyOWM 2.5 / Python 3.5: registry calls return "None"

### ISSUE THREAD

**Issue by lardconcepts** [csparpa/pyowm#150]
Following the example at https://github.com/csparpa/pyowm/wiki/Usage-examples#retrieving-city-id-for-a-location
```
    registry = owm.city_id_registry()
    print(registry.location_for("Gillingham"))
    print(registry.id_for("Gillingham"))
    print(registry.id_for("London,GB"))
```
I get ```None``` in all cases, whether I put UK, GB or just nothing after the town.

So I followed the docs at https://pyowm.readthedocs.io/en/latest/pyowm.webapi25.html#module-pyowm.webapi25.cityidregistry and read the source at https://github.com/csparpa/pyowm/blob/master/pyowm/webapi25/cityidregistry.py and put

```    registry = owm.city_id_registry('/usr/local/lib/python3.5/dist-packages/pyowm/webapi25/cityids/%02d-%02d.txt')```

and got ```TypeError: city_id_registry() takes 1 positional argument but 2 were given```

The town definitely exists:
```
/usr/local/lib/python3.5/dist-packages/pyowm/webapi25/cityids/103-108.txt
3106:Gillingham,2648657,51.389141,0.54863,GB
3107:Gillingham,2648658,51.03833,-2.27611,GB
```

I also found a reference to the registry not working back in January, here:
https://tasteandseejesus.com/2016/01/13/3-hour-forecasts-with-openweathermap-and-python/

**Comment by lardconcepts** [comment]
After poking around, I found that if you replace https://github.com/csparpa/pyowm/blob/master/pyowm/webapi25/cityidregistry.py#L80 
with ```if line.startswith(city_name.title())``` then it works in that it returns a value, but only the first one.

Trouble is, there are hundreds, maybe even thousands of towns and cities with the same name.
Do you want the Abbeville in France or any of the 4 in the US? Could it be altered to return a list which could be iterated through, like weather_at_place**s** does?

Example from first few lines of the first file:
```
123:Abasolo,3533505,24.066669,-98.366669,MX
124:Abasolo,4019867,25.950001,-100.400002,MX
125:Abasolo,4019869,20.450001,-101.51667,MX
138:Abbans-Dessus,3038800,47.120548,5.88188,FR
139:Abbans-Dessus,6452202,47.116669,5.88333,FR
148:Abbeville,3038789,50.099998,1.83333,FR
149:Abbeville,4178992,31.992121,-83.306824,US
150:Abbeville,4314295,29.974649,-92.134293,US
151:Abbeville,4568985,34.178169,-82.379013,US
152:Abbeville,4829449,31.57184,-85.250488,US
```

Here's what I use with weather_at_places to get my results and see which county it is in, other countries may have similar "geo-to-town" lookups... if registry returned a list, I could use this:
```
    resultlist = []
    search = owm.weather_at_places(location,searchtype='accurate')
    for results in search:
        l = results.get_location()
        country = l.get_country()
        name = l.get_name()
        if country == "GB" or country == "United Kingdom":
            lat = str(l.get_lat())
            lon = str(l.get_lon())
            ID = str(l.get_ID())
            data = requests.get("http://api.postcodes.io/postcodes?lon=" + lon + "&lat=" + lat + "&radius=1000")
````

**Comment by csparpa** [comment]
Closing this, as the buggy behaviour is tracked by #152 and the proposal about returning ID/Location lists is tracked by #153
