### ISSUE TITLE
Introduce deprecations

### ISSUE THREAD

**Issue by csparpa** [csparpa/pyowm#154]
We need a way to notify users that specific functionalities will be removed at some point in the future.
This way should reach as many users as possible, so I guess we need at least:

  - a wiki page for deprecations (for each PyOWM version, list what functionalities are marked as deprecated and what future version they will be dropped out of)
  - maybe something on the code-side. Eg: a silent decorator for functions to be deprecated, something like:

```python
@deprecated(removed_on_version=(3,0,0))
def my_functionality():
  ...
```

Once declared, deprecations cannot be removed, end-of-support version as well

**Comment by Diapente** [comment]
Maybe a changelog?

If there is clear documentation I can include it in the packaging for Arch - when you upgrade it would print out a message at the console saying what has been removed.

All best

N

**Comment by csparpa** [comment]
We do have a changelog [here](https://github.com/csparpa/pyowm/wiki/Changelog) and - yes - it would be a good place to notify deprecated functionalities and feature support drop!

**Comment by csparpa** [comment]
#155 fixes
