### ISSUE TITLE
weather.get_detailed_status for all cities gives wrong weather status

### ISSUE THREAD

**Issue by liendroid** [csparpa/pyowm#175]
I'm using the weather.get_detailed_status function and i noticed that no matter what city it's in, it'll always return back clear skies, but open weather site will say otherwise. 
For example, London currently is hazy, with broken clouds. But the function returns back clear skies. 
In order to get the weather, I used weather_at_place() and weather_at_ID().

**Comment by csparpa** [comment]
I've tagged it as "bug" just in case, but please @liendroid can you check out if the weather status given by the library is coherent to what the **API itself** is saying (__not the website__) ?

Cause the point here is: if the API is giving data different from the website, this would not be PyOWM's fault

Thanks

**Comment by liendroid** [comment]
You are correct, it looks like the API was returning a different value from the website. Strange, but not pyown's fault. Thanks for responding.
