### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode' in Python 3

### ISSUE THREAD

**Issue by Harmon758** [csparpa/pyowm#176]
`AttributeError: 'str' object has no attribute 'decode'` is raised in Python 3 when converting exceptions to strings, due to `self._message.decode('utf-8')` in `__str__`.

**Comment by csparpa** [comment]
@Harmon758 the fix is now on the develop branch - can you please give it a test? Thanks so much

**Comment by Harmon758** [comment]
Sorry for the _very_ late response, but yes, it's fixed now.
Thank you!

**Comment by csparpa** [comment]
:D no probs! thanks
