### ISSUE TITLE
time difference in weather forecast

### ISSUE THREAD

**Issue by jm33-m0** [csparpa/pyowm#179]
when requesting weather forecast for a city that's not covered in GMT, the result i get might be confusing due to time difference

**Comment by csparpa** [comment]
Hi @jm33-m0 I'm not sure I understand your question.. What do you mean when you say *"a city that's not covered in GMT"* ?

All OpenWeatherMap API timestamps are in GMT (better off to say: UTC) as stated [here](https://openweathermap.desk.com/customer/en/portal/articles/1634438-time-format-and-zone). PyOWM therefore returns timestamps/datatime objects in UTC timezone

**Comment by jm33-m0** [comment]
well, I meant if I look for weather forecast for a city that uses a timezone other than UTC, I'm still getting results based on UTC timezone, which, might be confusing to use

**Comment by csparpa** [comment]
Why would it be ?

All OpenWeatherMap timestamps are returned in UTC and that makes a lot of sense as weather forecasts are provided world-wide. Therefore PyOWM doesn't perform any timezone-translation

Timezone conversions can easily be done downstream using Python libraries such as [pytz](http://pytz.sourceforge.net/) or similar ones.

**Comment by jm33-m0** [comment]
even if I converted the timezone to UTC+8, the weather report is still based on UTC, which means, the time interval of `daily_forecast` that is supposed to be from 0:00 to 24:00 will be 8:00 to 32:00(8:00 in tomorrow morning)

**Comment by csparpa** [comment]
Sorry, I'm not sure I get it...

I mean, if you ask the OWM API for a daily forecast upon a UTC+8 city, I suppose the API will return results data relative to the time window 0:00 to 24:00 __local timezone__. Then, if the JSON it returns is containing any timestamp, this will be provided in UTC, and so PyOWM along.

Do you have any evidence in code that this behaviour is not as expected?

**Comment by jm33-m0** [comment]
with the following code, i made a query for `beijing,cn`
```python
def d_forecast(city):
    global owm
    global symbol
    fc = owm.daily_forecast(city)
    f = fc.get_forecast()
    fcst = {}
    day = 1
    for weather in f:
        # time = str(weather.get_reference_time('iso')).strip().split()[0]
        time = str(weather.get_reference_time('iso'))
        status = weather.get_status()
        wind = weather.get_wind()
        humidity = weather.get_humidity()
        temperature = weather.get_temperature('celsius')
        status = str(status).lower()

        fcst.update({str(day): symbol.get(status, status) + ' - ' + time + '\n' + '⚬ Wind: *' + str(wind['speed']) + ' kph*' + '\n' + '⚬ Humidity: *' + str(
            humidity) + '%*' + '\n⚬ Temperature: *' + str(temperature['min']) + ' °C ~ ' + str(temperature['max']) + ' °C*'})

        day += 1

    return fcst
```
and `fcst` looks like this:
```
{'2': '⛅ - 2017-04-12 04:00:00+00\n⚬ Wind: *2.71 kph*\n⚬ Humidity: *18%*\n⚬ Temperature: *2.65 °C ~ 22.53 °C*', '1': '☀ - 2017-04-11 04:00:00+00\n⚬ Wind: *2.56 kph*\n⚬ Humidity: *17%*\n⚬ Temperature: *5.47 °C ~ 12.0 °C*', '7': '🌧 - 2017-04-17 04:00:00+00\n⚬ Wind: *7.26 kph*\n⚬ Humidity: *0%*\n⚬ Temperature: *13.96 °C ~ 20.14 °C*', '5': '☀ - 2017-04-15 04:00:00+00\n⚬ Wind: *1.89 kph*\n⚬ Humidity: *0%*\n⚬ Temperature: *10.32 °C ~ 24.89 °C*', '6': '🌧 - 2017-04-16 04:00:00+00\n⚬ Wind: *1.81 kph*\n⚬ Humidity: *0%*\n⚬ Temperature: *14.0 °C ~ 16.43 °C*', '3': '🌧 - 2017-04-13 04:00:00+00\n⚬ Wind: *2.32 kph*\n⚬ Humidity: *27%*\n⚬ Temperature: *5.78 °C ~ 20.72 °C*', '4': '🌧 - 2017-04-14 04:00:00+00\n⚬ Wind: *2.61 kph*\n⚬ Humidity: *23%*\n⚬ Temperature: *5.14 °C ~ 25.78 °C*'}
```

**Comment by csparpa** [comment]
Yes, it's UTC and it's how it is supposed to be!

Let me try to clarify this with an example: the "lifecycle" of weather forecasts on Beijing (UTC+8) - let's take a forecast for day 2017-04-30

  1. OpenWeatherMap API computes the weather forecast for day 2017-04-12. As forecasts need to have  a reference timestamp and its format is not cut to only YYYY-MM-DD then hours minutes and seconds need to be specified: therefore, I guess OWM API takes midday as the reference timestamp, which is 2017-04-30 12:00:00+8 in local Beijing time, 2017-04-30 04:00:00+0 in UTC
  2. The forecast is delivered as a JSON document in response to your application's request. This carries the UTC timestamp (2017-04-30 04:00:00+0)
  3. PyOWM reads that JSON, builds the Forecast object and gives you that object. It does not change anything on the timestamps, that still are expressed in UTC.

Then,  if you want to have them in your local timezone, you need to bring back the UTC timestamps to local Beijing's timezone (UTC+8) - **but that's up to you**

How can you do it? Use [pytz](http://pytz.sourceforge.net), it's super easy!

Hope this helped :)

**Comment by jm33-m0** [comment]
thanks for the explanation, I think I need `forecaster` for more specific forecast 😂
