### ISSUE TITLE
Deg member missing in the get_wind() method

### ISSUE THREAD

**Issue by csparpa** [csparpa/pyowm#181]
As per title, reported by @InunoTaishou

The deg is inside the 16 day forecast api call but is dropped somewhere in PyOWM

**Comment by InunoTaishou** [comment]
```
import pyowm

owm = pyowm.OWM(api_key)
fc = owm.daily_forecast('64151,US', 1)
f = fc.get_forecast()
print(f.to_JSON())
```

> {"interval": "daily", "reception_time": 1491970369, "Location": {"name": "Riverside", "coordinates": {"lon": -94.6131, "lat": 39.1775}, "ID": 4405795, "country": "US"}, "weathers": [{"reference_time": 1491933600, "sunset_time": 0, "sunrise_time": 0, "clouds": 0, "rain": {}, "snow": {}, "wind": {"speed": 2.61}, "humidity": 52, "pressure": {"press": 1002.32, "sea_level": null}, "temperature": {"day": 286.7, "min": 277.63, "max": 286.7, "night": 277.63, "eve": 286.7, "morn": 286.7}, "status": "Clear", "detailed_status": "sky is clear", "weather_code": 800, "weather_icon_name": "01n", "visibility_distance": null, "dewpoint": null, "humidex": null, "heat_index": null}]}

http://api.openweathermap.org/data/2.5/forecast?q=64151,US&APPID=YOUR_API_KEY_HERE&cnt=1
> {"cod":"200","message":0.0042,"cnt":1,"list":[{"dt":1491976800,"main":{"temp":277.63,"temp_min":277.63,"temp_max":280.18,"pressure":1003.68,"sea_level":1038.77,"grnd_level":1003.68,"humidity":80,"temp_kf":-2.55},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],"clouds":{"all":0},"wind":{"speed":1.66,"deg":126.006},"sys":{"pod":"n"},"dt_txt":"2017-04-12 06:00:00"}],"city":{"id":4405795,"name":"Riverside","coord":{"lat":39.1775,"lon":-94.6131},"country":"US"}}

**Comment by csparpa** [comment]
@InunoTaishou hello, I've - possibly - fixed the issue, could you please test it out?

The fix is on the `develop` code branch.

I've tried out your code snippet reported above and it seems to work fine!

Thanks a lot

**Comment by Epy** [comment]
Thanks for fixing it :)
