### ISSUE TITLE
Can not get history, instead got BadGatewayError: <exception str() failed>

### ISSUE THREAD

**Issue by Naggi-Goishi** [csparpa/pyowm#192]
Hello, thank you for the library.
I found a bug when you try to get history of the whether. I got Bad Gateway Error.
I figured out that is due to change in the subdomain for getting history. I guess it change from `pro` to `history` .
So, the code for `_build_full_URL` should be change, thank you.

```
from pyowm import OWM
from datetime import datetime

coordinates = (35.68, 139.76)
now = datetime.now()
start_datetime = datetime(now.year, now.month, 1)
end_datetime = datetime(now.year, now.month, now.day, now.hour)

owm = OWM(MY_API_KEY, subscription_type='pro')
hist = owm.weather_history_at_coords(*coordinates, start=start_datetime, end=end_datetime)
print(hist)
```

**Comment by csparpa** [comment]
Thank you for notifying the bug!
I confirm that your analysis was right, the endpoint subdomain was changed.
Will fix it!

**Comment by csparpa** [comment]
Hello @Naggi-Goishi I've pushed a branch that should fix the subdomain change (along with some refactoring): https://github.com/csparpa/pyowm/tree/192_fix_history_endpoint

As I don't currently have - shame on me - a PRO OpenWeatherMap account (but I understood that you have one) would you please test the code out for me?
You can use the very same snippet you posted here to explain the issue.

Thanks, your help would be very appreciated
