### ISSUE TITLE
-compile failed with error code 1 in /tmp/pip-build-QuS6A8/pyowm

### ISSUE THREAD

**Issue by felinfo** [csparpa/pyowm#201]
Hello.

I've got this error when I have tried to install:

Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-QuS6A8/pyowm/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iUBubH-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-QuS6A8/pyowm
Storing debug log for failure in /home/pi/.pip/pip.log

Any help?

Thank you

**Comment by csparpa** [comment]
Hi @felinfo
Can you please tell what platform are you installing PyOWM on?
It would be good also if you could spot Pip log file and report the full error stack trace that is written on it upon the error
Thanks

**Comment by felinfo** [comment]
Hello csparpa.

I use Raspberry PI, Raspbian OS. I attach the pip.log file:

[pip.zip](https://github.com/csparpa/pyowm/files/1117681/pip.zip)

Thank you.

**Comment by csparpa** [comment]
@felinfo I guess you were trying to install with:

    python setup.py install

correct? If so, please don't install code from the `develop` branch, but from the `master` branch as it always contains the most recent working code.

Now, I took a look at the logfile you attached. At line 367 I see:

    error: could not create '/usr/local/lib/python2.7/dist-packages/pyowm': Permission denied

it lools like you're missing a `sudo` at the beginning of the command!

**Comment by felinfo** [comment]
Thanks, I solved with:

`sudo chown -R $USER /usr/local/lib/python2.7`
