### ISSUE TITLE
Pulling forecast data using list of ids

### ISSUE THREAD

**Issue by exoqrtx** [csparpa/pyowm#214]
I've been playing around with weather_at_ids and it seems to work a lot faster than individually pulling them using weather_by_id (although I haven't actually timed it, but it seems that way).  Looking through the docs I don't see a similar option for pulling forecasts by lists of id's, which would be really useful.  Is this a limitation of the source data or is this something that could added?

**Comment by csparpa** [comment]
Hi @exoqrtx I think this is a limitation of the OpenWeatherMap API

If you take a look here: http://openweathermap.org/current (look for "Call for several city IDs") they say there is an endpoint `/group` which returns a list of observations and takes as input a list of city IDs

Which does not happen - unfortunately - for forecasts: if you take a look here:
  - http://openweathermap.org/forecast5
  - http://openweathermap.org/forecast16
there is nothing similar to `/group`
