### ISSUE TITLE
will_be_sunny_at returns True even after sundown

### ISSUE THREAD

**Issue by niklasHagner** [csparpa/pyowm#215]
Thanks for a great lib. ⭐️  I've been trying it out for a while and it's been working great except for one thing:
- The function `fc.will_be_sunny_at` returns `True` long after sundown.

In sitting here in the darkness of winter-Stockholm during November, when sun sets around 15:30. 
Yet `fc.will_be_sunny_at` optimistically reports that it will be sunny tonight at 22:00 😄 
_(Unless I've completely messed up the datetime formatting, if so please let me know and delete this issue)_

Screendump (just to show how I'm calling `will_be_sunny_at` and what it returns, as well as what the location is specified as)
![screenshot](https://i.imgur.com/rC1Nmv3.png)

I did a bit of debugging, stepping via the `will_be_sunny_at` function into the`_will_be` function.
Here's a screen dump of the debugger state while on the last line of `_will_be`:
![vscodedebugger](https://i.imgur.com/RIsL5t1.png)

`weatherutils.status_is` would return true here.

From what I can tell on this screen dump, the `closest_weather` object doesn't contain any `sun` property at all.
So I'm confused why `weatherutils.status_is(closest_weather, 'sun', weather_code_registry)` returns True. But haven't had time to dig deeper.

Side note: Looking at the `closest_weather` object  in the sidebar, I notice that `_sunrise_time` and `_sunset_time` are both `0`. Could that be related to the issue?

**Comment by csparpa** [comment]
Hi and thanks for reporting!
I haven't debugged the code yet but the first thing that comes to my mind is: you might be mislead by the weather conditions named "sunny" and "sun"

I think these are equivalent and they both mean that the sky is clear (not cloudy)...you probably got that these convey the presence of the sun, which is not of course possible by night and by most of long Swedish winter days

Can you confirm?

Thanks

**Comment by csparpa** [comment]
@niklasHagner ping

**Comment by niklasHagner** [comment]
> you might be mislead by the weather conditions named "sunny" and "sun"
> I think these are equivalent and they both mean that the sky is clear (not cloudyy)

Yeah, seems like that is the case.

`will_be_sunny_at` is quite a misleading name. A better name would be something like `will_be_clear_at`.

**Comment by csparpa** [comment]
I absolutely agree with you

Also, the `will_be_sunny_at `method is specifically looking for the "sun" string as a value for the forecasted weather status... this means that we don't need a new name, but we need a new method also!

Thanks for notifying, I will open up a new feature issue for this

Cheers!
