### ISSUE TITLE
daily_forecast("Milan,it") fails with free API key

### ISSUE THREAD

**Issue by jaspereb** [csparpa/pyowm#216]
Thanks for the library, it's been super helpful. 

The Readme page example code failed with an invalid API key error. Not sure if they changed the pricing plan recently, but the daily forecast is not part of the free API, it would be great to have this commented because the rest of the library is so easy to get started with.

**Comment by csparpa** [comment]
Thanks for the suggestion @jaspereb !

I've removed it from the `README.md` file

Cheers!
