### ISSUE TITLE
Unauthorized error when using free api key for daily_forecast

### ISSUE THREAD

**Issue by gsimiao** [csparpa/pyowm#217]
Hi Claudio,

Thank you for maintaining this library. I am a beginner trying to get daily forecast information from OWM. According to the website it is possible to get 5 days/3 hour forecast with the free API, however I get an error when I use your daily_forecast method. I know my API key is working because I am able to get current condition information. I am using Python 3.5, Windows 10, Jupyter Notebook. Below is a sample code that produces this error. Any suggestions for how to get daily forecast info would be greatly appreciated. I am only looking for the forecast for today and tomorrow. Thanks.

Code:
from pyowm import OWM
API_key = 'I use my free API key'
location = 'Seattle, US'
owm = OWM(API_key)
fc = owm.daily_forecast(location)

Error: 
UnauthorizedError: Your API subscription level does not allow to perform this operation
Reason: Invalid API key

**Comment by csparpa** [comment]
Hi @gsimiao thanks for using PyOWM

I've just tried your code above using my personal free API key and it works... I get the forecast for Seattle

Did you retry at a different time? Maybe the API gave back an unexpected error. Also, you could try to sign up for a different API key in order to test the same code on your side.
If none of the above works, then I think the only way is to debug the code... in case pls let me know and we can instrument and IDE or similar

**Comment by gsimiao** [comment]
Thanks for the quick reply. I tried all the changes you suggested as far as a different time and a new API key from another account. I also tried using the IDE that comes with Python (that looks like notepad). Nothing worked. I wonder if it is something with my system. But in any case, I was using this library to test out the data that comes from OWM for an Arduino project that I am working on. I trust you that the info works and I don't want to put you through the effort of debugging the code since I will end up using a different library (for arduino) to access this data for my project. Thanks again.

**Comment by csparpa** [comment]
Please, don't go for another library - give PyOWM (and peace) a chance! :)

You said you were able to fecth observation data, but not forecast data. That is weird. I mean, I have an API key the same "clearance level" as yours, I should get the same issue as well but I don't.

Then the next unavoidable move would be debugging. If you choose to debug, don't use IDLE, use PyCharm or Eclipse. The line you need to debug is:

https://github.com/csparpa/pyowm/blob/a609632ac7a43bc64f43c8b003473160a8e4277a/pyowm/commons/weather_client.py#L58

I suggest to insert a print of the stack trace just before that line: this can be easily done with:

    import traceback
    traceback.print_exc()

Make sure that your Python script using PyOWM is run from a command line so you can take a look at the traceback and paste it here - if possible

Thanks!

**Comment by eventus17** [comment]
Hi Claudio!
I had the same issue. I commented lines below from the main example and it works:
```
forecast = owm.daily_forecast("Milan,it")
tomorrow = pyowm.timeutils.tomorrow()
forecast.will_be_sunny_at(tomorrow)
```
Didn't investigate the reason of this behavior. 

Appreciate Your work over pyowm! Thank You!
Regards Jacek

**Comment by csparpa** [comment]
Thanks @eventus17 

I just wanted to also ping @gsimiao about the "test" I've suggested above

I will try to debug the thing on Windows (it might be a platform issue?)

**Comment by eventus17** [comment]
> I will try to debug the thing on Windows (it might be a platform issue?)

I was running the example script on Win 10 after clean Python 2.7 installation

**Comment by gsimiao** [comment]
I am a beginner and unfortunately don't know enough to debug. Sorry

**Comment by csparpa** [comment]
Closing as this cannot be objectively proved to be an issue
