### ISSUE TITLE
Attribute Error OWM

### ISSUE THREAD

**Issue by PhilippTh** [csparpa/pyowm#218]
I always get AttributeError: module 'pyowm' has no attribute 'OWM' even when using the example code in the docs.

**Comment by csparpa** [comment]
Hi @PhilippTh I need you to provide more detail in order to be able to help you

Can you please paste here the exact code that is not working? Or at least a reference to the part of the docs you are referring to

Thanks

**Comment by PhilippTh** [comment]
Hi, thank you @csparpa for the quick response!
The code I'm using is from your example code in the docs folder.

from pyowm import OWM
API_key = 'I use my own API'
owm = OWM(API_key)
w = owm.daily_forecast(location)
print (w)

Thanks for the help!

**Comment by csparpa** [comment]
So... You said you have an installation on Ubuntu. Can you please launch the command

    pip show PyOWM

and paste here the full output of it?
Thanks man

**Comment by csparpa** [comment]
Also @PhilippTh please paste the output of

    pip3 show pyowm

My doubt is that you are using Python3 but installed PyOWM using `pip` for Python 2 !

**Comment by PhilippTh** [comment]
The outcome to both commands is:

```
C:\Users\Philipp>pip3 show pyowm
Name: pyowm
Version: 2.7.1
Summary: A Python wrapper around the OpenWeatherMap web API
Home-page: http://github.com/csparpa/pyowm
Author: Claudio Sparpaglione (@csparpa)
Author-email: csparpa@gmail.com
License: MIT
Location: c:\users\philipp\appdata\local\programs\python\python36\lib\site-packages
Requires:
```

**Comment by csparpa** [comment]
What interpreter did you use to run the code that fails?

Can you also pls enter that interpreter and paste here the output of:

    import sys
    print(sys.path)


Thanks

**Comment by PhilippTh** [comment]
I used the python interpreter

the command outputs
`['', 'C:\\Users\\Philipp\\AppData\\Local\\Programs\\Python\\Python36\\python36.zip', 'C:\\Users\\Philipp\\AppData\\Local\\Programs\\Python\\Python36\\DLLs', 'C:\\Users\\Philipp\\AppData\\Local\\Programs\\Python\\Python36\\lib', 'C:\\Users\\Philipp\\AppData\\Local\\Programs\\Python\\Python36', 'C:\\Users\\Philipp\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages']`

**Comment by csparpa** [comment]
@PhilippTh I've just tried to run your code on Linux+Python3.6.3 setup, it works like a charm...

Please bear with me and do this test for me please:
  1. use your Ubuntu setup, not Windows - what Ubuntu version is it?
  2. create a file with this code

```python
import traceback
try:
    raise ValueError()
except:
    traceback.print_exc()
```
and then run the file with the same interpreter that gave you the errors before.

Eventually, please paste here the stack trace. Thanks a lot

**Comment by PhilippTh** [comment]
I´d like to thank you for your patience with me and all the quick responses.

I tried this, and the output was:
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    raise ValueError()
ValueError

**Comment by csparpa** [comment]
My output was exactly as yours - you get the object printed out!

So you made it! Congrats!

Nobody will ever guess what the issue was, but that's OK as far as the library works ;)
