### ISSUE TITLE
leng or language

### ISSUE THREAD

**Issue by IlhamriSKY** [csparpa/pyowm#221]
owm = OWM(language='id',API_key=key)

i try language of indonesia and result always EN

**Comment by csparpa** [comment]
Hi @IlhamriSKY you didn't find it because your language is not among the ones supported by the OpenWeatherMap API (yet, at least). So you get English as a default.

You can find the list of supported languages [here](https://openweathermap.org/current), just look for "Multilingual support"

Cheers
