### ISSUE TITLE
ParseResponseError: Exception in parsing OWM web API response 

### ISSUE THREAD

**Issue by RaenonX** [csparpa/pyowm#224]
I got this error when I use the coordinates to try to get the weather data:
`Reason: pyowm.webapi25.forecastparser: impossible to read location info from JSON data `

Coordinates is 
```
latitude: -55.776573
longitude: 90.163473
```

**Comment by csparpa** [comment]
Hi @RaenonX  it might be that the OWM API is temporarily returning badly formatted JSON data (this happens seldom and usually is fixed upstream). But, it might also be that the change in the JSON format is voluntary and here to stay (and then we need to fix PyOWM accordingly)

Did you try to change the geocoords and see if you get the same error?
Also, did you repeat the call after a while? You get the sme error?

**Comment by csparpa** [comment]
@RaenonX 

```python
latitude = -55.776573
longitude = 90.163473
fc = owm.daily_forecast_at_coords(latitude, longitude)
tomorrow = pyowm.timeutils.tomorrow()
fc.will_be_sunny_at(tomorrow)
print(fc.get_forecast().get_location())
```

that actually works quite well to me

Did you try to repeat the call?

**Comment by RaenonX** [comment]
I am not at home now. I will try to repeat that codes after I go back home.

By the way, the function that I used and throws the error is
three_hours_forecast_at_coords (latitude, longitude).get_forecast()

**Comment by csparpa** [comment]
Thanks.

That's a bug! The JSON from the API has changed but the `Location` parser is not robust enough to return a "Null object" for the location bound to the forecast.

**Comment by RaenonX** [comment]
Haha, thanks for fixing the bug :)

**Comment by csparpa** [comment]
Fixed by https://github.com/csparpa/pyowm/commit/eb4ae017030079d57400ee8d4fb2f6a8802b8f5c
