### ISSUE TITLE
Accessing OWM pollution data

### ISSUE THREAD

**Issue by nikhilv-quantela** [csparpa/pyowm#228]
Is there a way to access air pollution data of Open Weather Map from pyowm

**Comment by csparpa** [comment]
Here we go: https://github.com/csparpa/pyowm/wiki/Air-Pollution-API:-Carbon-Monoxide-Index

**Comment by nikhilv-quantela** [comment]
Thanks a lot, understood.

Just one doubt, I got the value of coi like this.
`{'precision': 6.818107749495539e-07, 'pressure': 0.10000000149011612, 'value': -5.378958007895562e-07}`

Is negative volume mix ratio possible?

Thanks

**Comment by csparpa** [comment]
It looks like possible (though I have no idea about what it could mean on a chemical point of view :-/ )

On the OWM website, at this page: http://openweathermap.org/api/pollution/co you find examples responses with negative values for the `value` JSON attribute

I advise to drop a line to OWM tech support, just to be 100% sure they provide meaningful values

**Comment by nikhilv-quantela** [comment]
Thanks, will look into it
