### ISSUE TITLE
Regarding OWM Air Pollution SO2 and others

### ISSUE THREAD

**Issue by nikhilv-quantela** [csparpa/pyowm#229]
I was able to get CO Index and all as you taught in https://github.com/csparpa/pyowm/wiki/Air-Pollution-API:-Carbon-Monoxide-Index.
 But I was unable to get SO2, NO2, and O3 indices in similar fashion. Is that not accessible yet.

Thanks

**Comment by csparpa** [comment]
It is indeed man

Please read the pages on the wiki, all of these features are in place

**Comment by csparpa** [comment]
For your convenienve:

- O3: https://github.com/csparpa/pyowm/wiki/Air-Pollution-API:-Ozone
- NO2 and SO2: read [here](https://github.com/csparpa/pyowm/wiki/Changelog#whats-new-in-release-271) about the new methods, they work exactly as for O3

Sorry if the docs is not straightforward, I will fix it

**Comment by nikhilv-quantela** [comment]
Thanks a lot
