### ISSUE TITLE
Deadsnakes has moved!

### ISSUE THREAD

**Issue by asottile** [csparpa/pyowm#231]
Hello -- deadsnakes maintainer here.

Was doing a cursory sweep of github and noticed that your wiki [here](https://github.com/csparpa/pyowm/wiki/Project-Management-docs) still references the old ppa name (`ppa:fkrull/deadsnakes`).  The new ppa name is `ppa:deadsnakes/ppa` (or simply `ppa:deadsnakes` since the default ppa name is "ppa").

**Comment by csparpa** [comment]
Hey @asottile thank you very much for notifying!

I've patched references to `deadsnakes`
