### ISSUE TITLE
Twine update?

### ISSUE THREAD

**Issue by brainwane** [csparpa/pyowm#239]
Hi! I'm one of the maintainers of [Twine](https://pypi.org/project/twine/) and I saw that you specify an older version (we just released [version 1.11.0](https://pypi.org/project/twine/1.11.0/)) in your requirements. Please do let me know if there are any barriers to you upgrading? Thanks!

**Comment by csparpa** [comment]
Hello @brainwane !
No issues with upgrade - only me being too lazy in updating things :-D

The issue has been fixed with: https://github.com/csparpa/pyowm/commit/c7789b909781a30143a66f6c78331e8089aa65c6

Thanks for letting us know about it

**Comment by brainwane** [comment]
Thanks! Some folks use https://pyup.io/ to help remind them to upgrade new dependencies, in case you want to try that.
