### ISSUE TITLE
pyowm 2.8.0 has requirement requests<2.19

### ISSUE THREAD

**Issue by lardconcepts** [csparpa/pyowm#254]
Just did the regular `pip-review --local --interactive` and it brought requests up to the current version.

However, I then got this error:

`pyowm 2.8.0 has requirement requests<2.19,>=2.18.2, but you'll have requests 2.19.1 which is incompatible.`

Would be great to be able to use latest versions of both! Thanks for your great work on this.

**Comment by csparpa** [comment]
Hi! I've just happened to fix this yesterday (crystal ball!!) as the Travis-CI build broke for python 3.4 for this exact issue.. 

As honestly speaking there is no reason why requests should be <2.19 and requests uses semantic versioning, I've changed that to <3

**Comment by csparpa** [comment]
Fixed with 0d92adaa6b296b136772b6b179c97ad7f0accc4f
