### ISSUE TITLE
A nice logo for the project

### ISSUE THREAD

**Issue by csparpa** [csparpa/pyowm#255]
Community, please help! I am a terrible designer!! 

A few ideas about designing logos: https://about.twitter.com/en_us/company/brand-resources.html

Also provide a license for the logo

**Comment by marlinmm** [comment]
Hey, 
I have just started using pyowm for a project at my university and saw that you´re looking for a logo design.

What did you have in mind? I´m not a professional designer and created the design draft just for fun...
What do you think about it?

![open weather 2](https://user-images.githubusercontent.com/40545276/41822370-c4d4d52c-77ee-11e8-857a-cc4fab5cafdc.png)

**Comment by csparpa** [comment]
@marlinmm that's nice! Thanks! :)

I personally like it, but also would like to wait for a few more proposals to come in so we have more options to choose from

Let me also publicly ask the community about their opinion on the logo

**Comment by n0id** [comment]
@marlinmm how suitable, I like it!

**Comment by csparpa** [comment]
@marlinmm I could not resist, the logo is SO DAMN COOL! :) I've added it to the next release...

**Comment by marlinmm** [comment]
@csparpa I'm glad you guys liked it :)
Really awesome to be a small part of this cool project
