### ISSUE TITLE
pyowm==2.8.0 and requests==2.19.1 incompatibility

### ISSUE THREAD

**Issue by csparpa** [csparpa/pyowm#256]
The issue arises whenever one has `requests==2.19.1` installed and tries to install `pyowm==2.8.0`

Please refer to https://github.com/home-assistant/home-assistant/issues/15333 for a broader description.

The issue has fixed by modifying the `setup.py` so that requirements on requests are now `requests>=2.18.2,<3`

**Comment by csparpa** [comment]
Fixed with 0d92adaa6b296b136772b6b179c97ad7f0accc4f

**Comment by Pharizna** [comment]
Where is the setup.py?

**Comment by csparpa** [comment]
https://github.com/csparpa/pyowm/commit/0d92adaa6b296b136772b6b179c97ad7f0accc4f

**Comment by Pharizna** [comment]
Thank you but I can't find the file in that foler:
Thanks @csparpa but I can't find setup.py in your folder :(

`
pi@HASSIO:**/srv/homeassistant/lib/python3.5/site-packages/pyowm** $ ls -l

total 44

drwxr-xr-x 3 homeassistant nogroup 4096 Jan 18 20:12 abstractions

drwxr-xr-x 3 homeassistant nogroup 4096 Jan 18 20:12 caches

drwxr-xr-x 3 homeassistant nogroup 4096 Jan 18 20:12 commons

-rw-r--r-- 1 homeassistant nogroup 181 Jan 18 20:12 constants.py

drwxr-xr-x 3 homeassistant nogroup 4096 Jan 18 20:12 docs

drwxr-xr-x 3 homeassistant nogroup 4096 Jan 18 20:12 exceptions

-rw-r--r-- 1 homeassistant nogroup 2576 Jan 18 20:12 init.py

drwxr-xr-x 2 homeassistant nogroup 4096 Jan 18 20:12 pycache

drwxr-xr-x 4 homeassistant nogroup 4096 Jan 18 20:12 stationsapi30

drwxr-xr-x 3 homeassistant nogroup 4096 Jan 18 20:12 utils

drwxr-xr-x 5 homeassistant nogroup 4096 Jan 18 20:12 webapi25
`

Where it is?
