### ISSUE TITLE
API working for weather_at_place() but not owm.daily_forecast() or other calls

### ISSUE THREAD

**Issue by MichaelSternNYC** [csparpa/pyowm#266]
I have a couple of OpenWeatherMap free API keys. They work fine for 

```
owm = pyowm.OWM(MyFreeKey)
observation = owm.weather_at_place('Dobbs Ferry, US')
w = observation.get_weather()
```

but if I try

`forecast = owm.daily_forecast('Dobbs Ferry, US')`

I get the error

```
raise api_response_error.UnauthorizedError('Invalid API Key provided')
pyowm.exceptions.api_response_error.UnauthorizedError: Your API subscription level does not allow to perform this operation
```

Free API should give access to basic forecasts; what am I doing wrong?

**Comment by csparpa** [comment]
Hi

It looks like daily forecasts are not free of charge any more:

https://openweathermap.org/price

while3h forecasts still are :-/

**Comment by MichaelSternNYC** [comment]
5day / 3 hour forecast looks free to me. Was I using the wrong command for this API call? If so, what should I have done?

Thanks. 



Von meinem iPhone gesendet.

**Comment by csparpa** [comment]
If you're ok with 3 hours granularity forecasts (on a 5 days streak), then go with:

https://github.com/csparpa/pyowm/blob/197540db41cf90ce84d2e233f770b290de6d99ca/pyowm/webapi25/owm25.py#L473

What you did is call the daily_forecast() method which fetches 1 day granularity forecasts on a 16 days streak, but is on the paid tier as we said

Makes sense? Let me know!

**Comment by MichaelSternNYC** [comment]
Makes sense. I’ll try it when I get home tonight.

Thank you,

MS

**Comment by MichaelSternNYC** [comment]
Worked like magic. Thanks for checking.
