### ISSUE TITLE
Suddenly unable to use pyowm entirely.

### ISSUE THREAD

**Issue by IoIxD** [csparpa/pyowm#267]
My bot was working fine for the past few months, but yesterday it just stopped working suddenly.

> c:\Bots\bot_xd>main.py
> Traceback (most recent call last):
>   File "C:\Bots\bot_xd\main.py", line 2, in <module>
>     import pyowm
> ModuleNotFoundError: No module named 'pyowm'
> 
> c:\Bots\bot_xd>pip3 install pyowm
> Requirement already satisfied: pyowm in c:\users\owner\appdata\local\programs\python\python35-32\lib\site-packages (2.9.0)
> Requirement already satisfied: requests<3,>=2.18.2 in c:\users\owner\appdata\local\programs\python\python35-32\lib\site-packages (from pyowm) (2.19.1)
> Requirement already satisfied: geojson<2.4,>=2.3.0 in c:\users\owner\appdata\local\programs\python\python35-32\lib\site-packages (from pyowm) (2.3.0)
> Requirement already satisfied: idna<2.8,>=2.5 in c:\users\owner\appdata\local\programs\python\python35-32\lib\site-packages (from requests<3,>=2.18.2->pyowm) (2.7)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\owner\appdata\local\programs\python\python35-32\lib\site-packages (from requests<3,>=2.18.2->pyowm) (3.0.4)
> Requirement already satisfied: urllib3<1.24,>=1.21.1 in c:\users\owner\appdata\local\programs\python\python35-32\lib\site-packages (from requests<3,>=2.18.2->pyowm) (1.23)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\owner\appdata\local\programs\python\python35-32\lib\site-packages (from requests<3,>=2.18.2->pyowm) (2018.4.16)
> 
> c:\Bots\bot_xd>main.py
> Traceback (most recent call last):
>   File "C:\Bots\bot_xd\main.py", line 2, in <module>
>     import pyowm
> ModuleNotFoundError: No module named 'pyowm'

You can see from the above code I verified myself that I installed pyowm. I also installed it thorugh normal pip as well. Yet, for some reason suddenly, Python does not except pyowm.

I don't think it has to do with my code so I'm not including it here.

**Comment by csparpa** [comment]
:-) no problem, it happens!
