### ISSUE TITLE
OWM module not found

### ISSUE THREAD

**Issue by NikSudo** [csparpa/pyowm#268]
Hallo)

import pyowm
owm = pyowm.OWM('mykey')

observation = owm.weather_at_place('London')
w = observation.get_weather()
print (w)

and console get me:
`Traceback (most recent call last):
  File "/home/niksudo/projects/pyowm/pyowm.py", line 1, in <module>
    import pyowm
  File "/home/niksudo/projects/pyowm/pyowm.py", line 2, in <module>
    owm = pyowm.OWM("")
AttributeError: module 'pyowm' has no attribute 'OWM'
`

` pip show module pyowm
Name: pyowm
Version: 2.9.0
Summary: A Python wrapper around OpenWeatherMap web APIs
Home-page: http://github.com/csparpa/pyowm
Author: Claudio Sparpaglione (@csparpa)
Author-email: csparpa@gmail.com
License: MIT
Location: /usr/lib/python3.7/site-packages
Requires: geojson, requests
Required-by: 
`
`pip2 show module pyowm
Name: pyowm
Version: 2.9.0
Summary: A Python wrapper around OpenWeatherMap web APIs
Home-page: http://github.com/csparpa/pyowm
Author: Claudio Sparpaglione (@csparpa)
Author-email: csparpa@gmail.com
License: MIT
Location: /usr/lib/python2.7/site-packages
Requires: requests, geojson
Required-by: 
`

**Comment by csparpa** [comment]
Hi @NikSudo sorry for the delay in answering you

I've tried your same code with your same Python interpreter and no signs of any bug on my side

Were you able to figure out what went wrong ?

**Comment by csparpa** [comment]
not an issue, closing
