### ISSUE TITLE
 Sub-directory

### ISSUE THREAD

**Issue by Nickduino** [csparpa/pyowm#284]
It's  probably be a pip issue (by "issue", I mean user error) rather than a pyown own but I don't get why the example file works in the /home/pi/ directory but not in /home/pi/Pi-Somfy:

![image](https://user-images.githubusercontent.com/9784237/52429790-0e85ee80-2b05-11e9-8ebf-5f274dcff308.png)

Can someone help?

**Comment by Nickduino** [comment]
And in Python 3.5:

![image](https://user-images.githubusercontent.com/9784237/52431007-9ff66000-2b07-11e9-8768-8bf81edb1687.png)

**Comment by Nickduino** [comment]
Never mind, solved it

**Comment by csparpa** [comment]
:-D

**Comment by Nickduino** [comment]
And thanks for the code, Claudio!
