### ISSUE TITLE
AgroMonitor API - Soil temp is not always a float

### ISSUE THREAD

**Issue by geofbaum** [csparpa/pyowm#288]
From #245 soil temp reported back by the API may not always be a float which will cause an error to be thrown due to the asserts in the __init__ section of the soil.py file. One might also assume though, I have not tested it, that depending on the soil data source and polygon location that the value could also return a None. However, the issue here is mainly that the Soil Temp could be returned as an integer or float.

**Comment by csparpa** [comment]
Fixed in real time :)
still need to push the commit....
thanks for pointing this out!

**Comment by geofbaum** [comment]
No problem, glad I could help!
