### ISSUE TITLE
No module named 'pyown'

### ISSUE THREAD

**Issue by demix506** [csparpa/pyowm#290]
Good evening. I have a problem. When I run the program, I get the error: "No module named 'pyown'" I reinstalled the python, and also removed all the plugins and reinstalled "pyown". Well, anyway there is an error, what to do?

**Comment by geofbaum** [comment]
@demix506 just to make sure this isn't just a simple spelling problem, are you typing in pyowm or pyown as you've written above?

You should be using something such as the following that you see in the documents.

```python
from pyowm import OWM```

**Comment by demix506** [comment]
im fix
