### ISSUE TITLE
coveralls is not working on develop

### ISSUE THREAD

**Issue by edenhaus** [csparpa/pyowm#304]
Ciao Claudio,

Since the commit 9adfae5941a8bda562def5710c9435614c93c726 the Coveralls is not anymore working and shows a coverage of 0%.

**Comment by csparpa** [comment]
Ciao!

it looks like we're facing another instance of the "but how is that possible? it's working like a charm on my PC!" non-written principle of software engineering :)

Have you installed the deps specified in https://github.com/csparpa/pyowm/blob/develop/dev-requirements.txt ?

Can you pls post the output of a `tox `run ?

Thanks

**Comment by edenhaus** [comment]
I did not run it locally. I only check it online on the website: https://coveralls.io/github/csparpa/pyowm?branch=develop

**Comment by csparpa** [comment]
...and back to green! https://coveralls.io/builds/30228842
96% coverage, not that bad after all
