### ISSUE TITLE
Add OneCall docu and add more tests

### ISSUE THREAD

**Issue by edenhaus** [csparpa/pyowm#307]
See https://github.com/csparpa/pyowm/pull/306#issuecomment-619549255

@csparpa You can assign this issue to me. It is better to have an issue as to comment on a merged pull request. This week is already full with uni and work, but I think I can do it next week.

**Comment by csparpa** [comment]
@edenhaus I've written tests for `weather_manager.one_call` and `weather_manager.once_call_history` functions

Up to you writing tests for the `OneCall` class then

**Comment by edenhaus** [comment]
@csparpa nice :) I have already written some basic unit tests in the original PR. As OneCall uses the weather class, I think this enough tests for the moment. So I will concentrate on the docs next week

**Comment by csparpa** [comment]
There is no release date but I would love to release v3 as soon as possible so that people can start using the OneCall feature as a swap-in replacement for the dead DarkSky API

No need to hurry!

**Comment by edenhaus** [comment]
Nice. I will then include the new version into home assistant as I will use oneCall to get the forecast for my smart irrigation
