### ISSUE TITLE
AttributeError: "OWM" object has no attribute

### ISSUE THREAD

**Issue by LkiZt** [csparpa/pyowm#315]
Start code in cmd and always have an AttributeError: "OWM" object has no attribute
pip install pyown was successful
Code:
import pyowm

owm = pyowm.OWM("*My API*")

place = input(" ")

observation = owm.weather_at_place(place)
w = observation.weather
print(w)

![image](https://user-images.githubusercontent.com/66335920/83571908-536f3900-a531-11ea-8f80-2d6c36bb37a0.png)

**Comment by csparpa** [comment]
Hi @LkiZt this happens because now PyOWM is at version 3  and your code thinks it is version 2.x
PyOWM 3 is a **major release** - therefore breaking compatibility with v2 client programs

The patch is easy: instead of

```
import pyowm

owm = pyowm.OWM("My API")

place = input(" ")

observation = owm.weather_at_place(place)
w = observation.weather
print(w)
```

just:

```
import pyowm

owm = pyowm.OWM("My API")

place = input(" ")

mgr = owm.weather_manager()                 # <<<<<
observation = mgr.weather_at_place(place)   # <<<<<

w = observation.weather
print(w)
```

Let me know if this works for you

**Comment by LkiZt** [comment]
Hi @csparpa that works. Thank you
