### ISSUE TITLE
Documentation: need clarification on getting temperature from a forecast object

### ISSUE THREAD

**Issue by originalsurfmex** [csparpa/pyowm#327]
I'm having trouble getting the temperature from a forecast object.  Specifically, I'm using `forecast_at_place`

Is this possible in PyOWM 3 or should I be combining this with other parts of the API?

**Comment by csparpa** [comment]
Hi @originalsurfmex of course it is possible!
Take the code [here](https://pyowm.readthedocs.io/en/latest/v3/code-recipes.html#get-forecast-on-a-location): let me paste it here for you,

```python
from pyowm.owm import OWM
owm = OWM('your-api-key')
mgr = owm.weather_manager()
daily_forecast = mgr.forecast_at_place('Berlin,DE', 'daily').forecast  # this gives you a FORECAST object
```

The `daily_forecast` object basically contains a list of `Weather` objects, on for each of the next days in this case

So you should simply iterate over them this way, and for each one extract the embedded temperature data:

```python
for weather in daily_forecast:
    print(weather.temperature(unit='celsius')  # can be also kelvin and fahrenheit
```

Could this work out to you ?
Let me know

**Comment by originalsurfmex** [comment]
Got it! I wasn't adding the unit so it was coming in blank.  Thanks!
