### ISSUE TITLE
weather_manager

### ISSUE THREAD

**Issue by will3dev** [csparpa/pyowm#329]
Hello,

I am getting the below error when trying to call `owm.weather_manager() `using the code described in the quick start.

AttributeError: 'OWM25' object has no attribute 'weather_manager'

Below is the code being used. Other functions from OWM seem to be working.

```
owm = OWM(key)
mgr = owm.weather_manager()

observation_list = mgr.weather_around_coords(40.75, -73.99)
w_ny = observation_list.weather
print('temperature:', w_ny.temperature('fahrenheit'))
```

**Comment by csparpa** [comment]
Hi
The documentation refers to PyOWM v3
I guess you are using PyOWM v2 instead, right?
If so, pls make sure you install PyOWM v3 which requires python 3.6+
