### ISSUE TITLE
AttributeError: 'OWM25' object has no attribute 'weather_manager'

### ISSUE THREAD

**Issue by neiry** [csparpa/pyowm#331]
mgr = owm.weather_manager()
AttributeError: 'OWM25' object has no attribute 'weather_manager'
error (((( pls help

**Comment by csparpa** [comment]
@neiry Pls run one of these:
```python
print(owm)
print(owm.version())
```

and report your PyOWM version
This is very likely due to your PyOWM version not being 3.x 
Are you using Python 2 ?

**Comment by neiry** [comment]
py 3-x
OWM 3/0

**Comment by neiry** [comment]
sorry Successfully installed pyowm-2.9.0

**Comment by csparpa** [comment]
As I said, you are using a legacy version (2.9) of PyOWM
That version is no longer maintained and the documentation on readthedocs refers to the official (3.x) PyOWM stream

**My advice is to update to Python3 and then to update PyOWM to v3**

If you are forced by any reason to keep Python2 and PyOWM 2.9 then [at this link](https://github.com/csparpa/pyowm/tree/efabe6abb6a4f32f4498a7ca5343563c804fcaa5/sphinx) you can find all the documentation files for v2.9
