### ISSUE TITLE
pinned and limited PySocks==1.7.1,<2 ???

### ISSUE THREAD

**Issue by onkelbeh** [csparpa/pyowm#334]
setup.py:
```python
install_requires=[
        'requests>=2.20.0,<3',
        'geojson>=2.3.0,<3',
        'PySocks==1.7.1,<2',
        'requests[socks]'
    ]
```
makes no sense.
In general, versions should be pinned only with a reason.
Thanks a lot.

**Comment by csparpa** [comment]
Hi @onkelbeh 

version had been pinned to avoid major version updates on dependencies breaking PyOWM

Is there something I am missing here? Extra-zeal on my side?

**Comment by onkelbeh** [comment]
Yep, you already pin 'PySocks==1.7.1' so the second constraint '<2' is already fulfilled.

Found this during compile and constraints tests for [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository).
Hope you don't mind I added your component to it.

**Comment by csparpa** [comment]
@onkelbeh - Man, I'm happy that PyOWM is useful! :)

Ok so `PySocks>=1.7.1,<2' woul work OK - am I right ? No more pinning and no major version disruptions

**Comment by csparpa** [comment]
In the `development` branch
