### ISSUE TITLE
state/country mismatch for toponyms generated by locations_for method

### ISSUE THREAD

**Issue by Darumin** [csparpa/pyowm#335]
Not sure if this is something that needs attention:

`locations_for()` method in CityIdRegistry returns a list of Location objects with toponyms.

However, it isn't always a "city, country" stored in Location object. For every US state, it returns the state instead of the country.

Similarly, this doesn't seem to match `weather_at_place()` under weather manager. If you try using this method with a "city, us state" query, you won't get results.

Please let me know if there's something I'm missing. Thank you.

**Comment by Darumin** [comment]
I discovered that this is the nature of the OpenWeather API, not necessarily a bug. Lookups with the format "city name, US state, country" do work here, but "city name, US state" alone will not work.

**Comment by csparpa** [comment]
@Darumin well done! thanks for investing in this
