### ISSUE TITLE
Add list of supported languages

### ISSUE THREAD

**Issue by Misiu** [csparpa/pyowm#339]
Currently, in Home Assisnatt the list of supported languages is added to Home Assistant, but as [suggested by one of the contributors](https://github.com/home-assistant/core/pull/40448#pullrequestreview-493903276), ideally it should be added to your package.
My [recent PR](https://github.com/home-assistant/core/pull/40448) is adding the whole list of languages from OWM website.

Consider adding this as a const.

**Comment by csparpa** [comment]
Thanks, will do.
I will try to use standard ISO labelling for supported languages

**Comment by Misiu** [comment]
Thanks, looking forward to that!
The list of supported languages is here: https://openweathermap.org/forecast5#multi
In my PR I've added the following list:

```
LANGUAGES = [
    "af",
    "al",
    "ar",
    "az",
    "bg",
    "ca",
    "cz",
    "da",
    "de",
    "el",
    "en",
    "es",
    "eu",
    "fa",
    "fi",
    "fr",
    "gl",
    "he",
    "hi",
    "hr",
    "hu",
    "id",
    "it",
    "ja",
    "kr",
    "la",
    "lt",
    "mk",
    "nl",
    "no",
    "pl",
    "pt",
    "pt_br",
    "ro",
    "ru",
    "se",
    "sk",
    "sl",
    "sp",
    "sr",
    "sv",
    "th",
    "tr",
    "ua",
    "uk",
    "vi",
    "zh_cn",
    "zh_tw",
    "zu",
]
```

**Comment by csparpa** [comment]
Ok @Misiu , it's in.

Commit eb1f943e804e1a056a49e95a35744eca80b0e1ae on branch `develop`

As easy as:

```python
from pyowm.owm import OWM
owm = OWM('your-api-key')
owm.supported_languages
```

```

**Comment by Misiu** [comment]
@csparpa that was quick 😃 
can I use that const without creating an OWM instance?
I need to get a list of supported languages before I create owm.
Sorry for a newbie question but I'm new to Pyhon.

**Comment by csparpa** [comment]
Yes you can, the constant is in module

https://github.com/csparpa/pyowm/blob/develop/pyowm/constants.py

Just import that with:

```python
from pyowm.constants import LANGUAGES
```


Claudio Sparpaglione
csparpa@gmail.com
http://linkedin.com/in/claudiosparpaglione

**Comment by Misiu** [comment]
@csparpa thank you 👍
now let's wait for 3.1 to get released.
