### ISSUE TITLE
Precipitation from minutely forecast is not stored in Weather

### ISSUE THREAD

**Issue by Tobiaqs** [csparpa/pyowm#343]
One-call JSON response (for locations that support minutely forecasts) looks like this:

```
{
  "minutely": [{ "precipitation": 0.443, "dt": 1601552873 }, ...],
  ...
}
```

All objects in the minutely array are parsed using `Weather.from_dict` but this ignores the precipitation field.

Possible solution: if `precipitation` is in the input of `Weather.from_dict`, set the `rain` field to `{ "1m": the_dict['precipitation'] }`

**Comment by csparpa** [comment]
Bad luck!! :-Z
Can you submit a PR about it?

**Comment by Tobiaqs** [comment]
Will do soon!

**Comment by Tobiaqs** [comment]
PR created. Could you give us an ETA for when this will reach master?

**Comment by csparpa** [comment]
Tomorrow, reasonably!

**Comment by csparpa** [comment]
Fixed with #344

**Comment by csparpa** [comment]
@Tobiaqs 3.1.1 is on PyPi --> you owe me a beer ;-)
hope this is helpful!

**Comment by Tobiaqs** [comment]
Awesome, thanks a lot!
