### ISSUE TITLE
New matching method

### ISSUE THREAD

**Issue by roman465** [csparpa/pyowm#348]
When you search for a city by name, three matchings are available: 'exact', 'nocase', and 'like'. They were not suitable for the app I'm working on, so I came up with a new matching that I called 'startswith'. It matches the city from the beginning of the name, and you don't have to type the entire name. Please see the screenshot to understand better what it looks like and how it is different from 'like'.
Like other matchings, it works with "geopoints_for", "ids_for", "locations_for". I haven't written any unit tests, though.
I wanted to contribute to this project, but it requires a lot of work with testing and documentation changes (at least at first glance). I'm not even sure if it's something anyone needs except me. So I wanted to ask your opinion on this. Would this feature be useful? Thanks.

![image](https://user-images.githubusercontent.com/25715951/96654729-d869bc00-1333-11eb-8746-2f5161188d5c.png)

**Comment by csparpa** [comment]
Hello, It definitely would!! would you submit a PR with a few tests an docs fixes? I can integrate it further if you don't have the time. but anyway, no hurry on this. thanks!

**Comment by roman465** [comment]
Yes, I'll write a few tests and submit a PR when I have more free time. Thanks for your reply!
