### ISSUE TITLE
Add new pop field to Weather class (probability of precipitation)

### ISSUE THREAD

**Issue by gpoppino** [csparpa/pyowm#354]
Hello,

There is a new *pop* field in the response of weather data that shows the probability of precipitation in a day.

Example response:

* https://openweathermap.org/forecast5#JSON

Announcement:

* https://openweathermap.medium.com/probability-of-precipitation-in-openweather-forecasts-f746db1e8c1

Could this new field be added to the Weather class?

**Comment by csparpa** [comment]
Hello @gpoppino I think we've already got this into the `develop `branch (see: https://github.com/csparpa/pyowm/pull/349)

This will be in the next release, if you need it urgently you can install PyOWM from the develop branch, [which I strive to keep always stable](https://travis-ci.org/github/csparpa/pyowm/builds/740001094)

**Comment by gpoppino** [comment]
Hi, that's great news! I think I will wait for the next release. Thanks!

**Comment by MatthiasLohr** [comment]
When will this next release be released? Also awaiting this feature/field...

**Comment by csparpa** [comment]
@MatthiasLohr I am not able to schedule a release date as of today.. the feature is already available on the develop branch, if you need it urgently please install pyowm by cloning that branch (follow the project docs here https://pyowm.readthedocs.io/en/latest/v3/faq.html#modulenotfound-error-upon-installing-pyowm-development-branch-from-github at the very bottom)

**Comment by csparpa** [comment]
@MatthiasLohr FYI by today the next PyOWM release will be out!
