### ISSUE TITLE
Is it longer available ?

### ISSUE THREAD

**Issue by DamienFoulon** [csparpa/pyowm#356]
Hi everyone,

I would like to download your module but I encountered a little problem wich is also a big 'coz I can't download it :/
`$ pip install pyown
 ERROR: Could not find a version that satisfies the requirement pyown (from versions: none)
 ERROR: No matching distribution found for pyown`

Si I tried with pip3 but I got the same error :/ 

So is it longer available ???

**Comment by csparpa** [comment]
@DamienFoulon yes it is available. you have a typo in your statement: you write "pyown" but you should write "pyowm" instead (watch out for the final letter)
