### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XMY400013** [csparpa/pyowm#371]
owm = OWM('Key')# instation Client Owm API
mgr = owm.weather_manager()# instation manager
mgr.forecast_at_coords(lat, lon, 'daily')# get forecast interval - daily
///    raise exceptions.UnauthorizedError('Invalid API Key provided')
pyowm.commons.exceptions.UnauthorizedError: Invalid API Key provided

**Comment by csparpa** [comment]
@XMY400013 OWM has restricted the Daily Forecast API, so it is not available for free users. They advice to use the One Call API instead, to get a daily forecast on the free plan 

Please  use PyOWM OneCall functions then...

Thanks!

**Comment by XMY400013** [comment]
thanks for the clarification!
