### ISSUE TITLE
OpenWeather Map v3 How To Configure Caching

### ISSUE THREAD

**Issue by dcs3spp** [csparpa/pyowm#384]
Hi,

In previous [versions](https://pyowm.readthedocs.io/en/2.10/usage-examples-v2/weather-api-object-model.html) it was possible to customise caching strategy.

Since that time it looks as though OWM25 has been refactored and renamed to OWM. How to specify caching with pyowm v3?

**Comment by csparpa** [comment]
Hello, since PyOWM version 3 out-of-the-box caching has been dropped. This was a design decision. Therefore caching is to be provided directly by clients of the PyOWM library

**Comment by dcs3spp** [comment]
Ok, many thanks @csparpa, appreciated :)
