### ISSUE TITLE
Please add support for One Call alerts

### ISSUE THREAD

**Issue by IceBotYT** [csparpa/pyowm#391]
I really like using One Call to get weather alerts, because it's easy and simple.
You can find docs on that [here](https://openweathermap.org/api/one-call-api#parameter) (ctrl+f, type "alerts")

**Comment by csparpa** [comment]
@IceBotYT thanks for submitting this feature request
Would you feel like helping out on this?

**Comment by IceBotYT** [comment]
> @IceBotYT thanks for submitting this feature request
> Would you feel like helping out on this?

I would love to, but I went through and the code was a little confusing for me to contribute. Sorry :(

If you helped me understand the structure of the source code maybe I’d help 😁

**Comment by IceBotYT** [comment]
I looked at it again, and I think I'm able to help contribute :)

**Comment by IceBotYT** [comment]
I just noticed that you already have some work on this feature on the `develop` branch! Mind committing that? https://github.com/csparpa/pyowm/commit/1d6a922cb8231ca66719ab2649544e9e4c610b47

**Comment by csparpa** [comment]
Please @IceBotYT you're very welcome to build upon what is on the `develop` branch and submit a pull request when you're done!!
Take your time to properly also unit test the code
Thanks!!

**Comment by IceBotYT** [comment]
Closed as [this release](https://github.com/csparpa/pyowm/releases/tag/3.3.0) has resolved the issue
