### ISSUE TITLE
AssertionError at initialization NationalWeatherAlert 

### ISSUE THREAD

**Issue by xavaxov** [csparpa/pyowm#399]
Hi! When i initialize variable one_call

`one_call = mgr.one_call(lat=59.964265, lon=30.148780)`

sometimes i have AssertionError

`File "/Library/Python/3.7/site-packages/pyowm/weatherapi25/national_weather_alert.py", line 33, in __init__
    assert sender, 'Event sender name must be specified'
AssertionError: Event sender name must be specified`

It's happen when whether forecast has Weather alerts without sender name or description. As i understand it not usual for every country, for example in Germany it's not a problem because Weather alerts has all attributes.

My program worked correctly if i comment 2 rows in library like that:
```
 def __init__(self, sender, title, description, start_time, end_time, tags=None):
        # assert sender, 'Event sender name must be specified'
        assert title, 'Event title must be specified'
        # assert description, 'Event description must be specified'
        assert start_time, 'Event start time must be specified'
        assert end_time, 'Event end time must be specified'
```

How can i get around this assert or can you fixed this, please.

Thanks!

**Comment by geofbaum** [comment]
@csparpa Just in case you haven't seen what the normal request sends back here's an example I just found.  Location I used was also in Russia (lat=69.02754, lon=48.93540) after I checked to see if there was an alert. sender_name and description are just blank strings at least for the English part of the response, in the Russian part of the response it's just the sender_name that is blank.

```json
'alerts': [{'sender_name': '',
   'event': 'Wind',
   'start': 1652612400,
   'end': 1652637600,
   'description': '',
   'tags': ['Wind']},
  {'sender_name': '',
   'event': 'Ветер',
   'start': 1652612400,
   'end': 1652637600,
   'description': 'местами порывы 15 м/с',
   'tags': ['Wind']},
  {'sender_name': '',
   'event': 'Fog',
   'start': 1652612400,
   'end': 1652680800,
   'description': '',
   'tags': ['Fog']},
   ```

**Comment by csparpa** [comment]
@geofbaum Thanks for helping out on this
@xavaxov I've submitted a fix, but if you can't wait for a new release you can apply the patch to your local PyOWM code yourself (it's just about commenting/removing 2 lines of code, see https://github.com/csparpa/pyowm/commit/f27876f5d679254b709f8a7ac9998c23ff02a289#diff-d915279e6cb4f4dc8b341f2203070a0c9f89fb1af3c42994fda7e5a3a15e72df):
