### ISSUE TITLE
Cannot find package on Anaconda

### ISSUE THREAD

**Issue by f-riente** [csparpa/pyowm#402]
Hello,

I'm having issues installing the pyowm package from anaconda. 
The package is supposed to be there: 

https://anaconda.org/auto/pyowm

but it is more than 8 year old. Do you have any suggestions on how to install it?
Downloading directly the version 3.3.0.tar.gz and installing it doesn't seem to work.

Thanks for you support.

**Comment by csparpa** [comment]
I'm sorry @f-riente but I know nothing about the Conda distribution of PyOWM. Please contact the Conda community if you want to understand why they ship an outdated PyOWM release.

I suggest you to use `pip install pyowm` in order to get the latest PyOWM version (3.3.0 as of today)
