### ISSUE TITLE
Parsing visibility exception

### ISSUE THREAD

**Issue by alexschultze** [csparpa/pyowm#70]
Parsing fails for some stations parsing fails with exception.

https://gist.github.com/alexschultze/5c94bb13422c44d06161

here is an example that fails:

{u'clouds': {u'all': 0}, u'name': u'Berlin Koepenick', u'visibility': 10000, u'sys': {u'country': u'DE', u'sunset': 1427304457, u'message': 0.0141, u'type': 1, u'id': 4878, u'sunrise': 1427259349}, u'weather': [{u'main': u'Clear', u'id': 800, u'icon': u'01n', u'description': u'Sky is Clear'}], u'coord': {u'lat': 52.44, u'lon': 13.55}, u'base': u'stations', u'dt': 1427327222, u'main': {u'pressure': 1004, u'temp_min': 282.15, u'temp_max': 284.26, u'temp': 283.39, u'humidity': 70}, u'id': 2885657, u'wind': {u'speed': 3.6, u'deg': 90}, u'cod': 200}

**Comment by csparpa** [comment]
It should be fixed now... please report back again if you get more parsing exceptions!
