### ISSUE TITLE
weather_at_id function

### ISSUE THREAD

**Issue by vubo** [csparpa/pyowm#82]
@csparpa Hi!

I use:
```
obs = owm.weather_at_id(2940132)
```
It works not with all IDs. For example this station: http://api.openweathermap.org/data/2.5/station?id=121479 

```
obs = owm.weather_at_id(121479)
ERROR: OWM API: observation data not available - response payload: 
{"message": "Error: Not found city", "cod": "404"}
```

**Comment by csparpa** [comment]
Hi @vubo, thanks for posting this.

It looks like that the OWM API is not providing data for that station. If you try:

    http://api.openweathermap.org/data/2.5/weather?id=121479

you get

    {"cod":"404","message":"Error: Not found city"}

Unfortunately I can't do anything about it :-(
Can you test this out a little bit more and - if confirmed - post an issue on the OWM channels (eg: bug tracker on their website, Facebook group)?

Thanks

**Comment by vubo** [comment]
@csparpa thank you, I will ask OWM.
