### ISSUE TITLE
Cannot pass string into `CityIDRegistry._match_line`

### ISSUE THREAD

**Issue by ggstuart** [csparpa/pyowm#85]
This code in the [`CityIDRegistry` class](https://github.com/csparpa/pyowm/blob/master/pyowm/webapi25/cityidregistry.py#L75) doesn't work for me in python 3.3.4.

```python
def _match_line(self, city_name, lines):
        for line in lines:
            if line.startswith(city_name.lower()):
                return line.strip()
        return None
```

So I can't lookup a city like this

```python
registry = owm.city_id_registry()
result = registry.location_for("London")
```

Because it fails like this.

> TypeError: startswith first arg must be bytes or a tuple of bytes, not str

I believe the problem is that the `lines` variable contains bytes, not strings. This means that `if line.startswith(city_name.lower()):` fails when `city_name` is a string.

To compound this, I can't simply pass in bytes like this.

```python
registry = owm.city_id_registry()
result = registry.location_for(bytes("London", 'utf8'))
```

because `CityIDRegistry._assess_subfile_from` uses `ord()` which requires a string.

A solution may be to add a line like this.

```python
def _match_line(self, city_name, lines):
        city_name = bytes(city_name.lower(), 'utf8')
        for line in lines:
            if line.startswith(city_name.lower()):
                return line.strip()
        return None
```

**Comment by csparpa** [comment]
This commit fixes the issue: https://github.com/csparpa/pyowm/commit/78ec1071d650de8cf69ff2793ea1a5c141f4a5fb

Sorry for not creating a specific feature branch but I forgot :-p
