### ISSUE TITLE
Can it use it for Flask as well as Tornado?

### ISSUE THREAD

**Issue by scheung38** [csparpa/pyowm#87]
Because I would like automatic update from server, could this be done in Flask or do I need to use Tornado? Thanks

Seb

**Comment by csparpa** [comment]
Hi, I'm not sure I get your point. Anyway, as it is not depending on any framework, you can use PyOWM on Flask (as well as on Django).
For what concerns Tornado, please notice that PyOWM is not designed with asynchronicity in mind: this furthermore is a very good chance to check PyOWM behaviour in async contexts (eg: Tornado's async methods)
If you can provide help on this that would be FANTASTIC!!! :)

**Comment by csparpa** [comment]
No feedback provided, closing...
