### ISSUE TITLE
Humidity = 0 when using weather_from_station

### ISSUE THREAD

**Issue by dstmar** [csparpa/pyowm#91]
Using pyowm 2.2.1, there's an issue in webapi25.weather in weather_from_dictionary.  The humidity when using weather_from_station() is under d['last']['main']['humidity'], so an additional condition should be checked before the else: humidity = 0:

elif 'last' in d and 'main' in d['last'] and 'humidity' in d['last']['main']:
        humidity = d['last']['main']['humidity']

Adding this condition fixed the get_humidity() for me.

**Comment by csparpa** [comment]
Thanks for pointing this out!
@dstmar can you submit a pull request fixing the issue?

**Comment by csparpa** [comment]
Fixed with #96 

@dstmar the fix is on development version for the moment :)
