### ISSUE TITLE
PyOWM handling NaNs

### ISSUE THREAD

**Issue by Tangerino** [csparpa/pyowm#95]
observation = owm.weather_at_I don't for
{"_id":5880054,"name":"Barrow","country":"US","coord":{"lon":-156.788727,"lat":71.290581}}
Is returning Nan even in theirs web site.
I care about just the temperature, can we overcome this problem?
Thanks
Carlos

**Comment by csparpa** [comment]
Hi @tangerino can you please provide a snippet with the code you're using so I can reproduce the output? Thanks

**Comment by Tangerino** [comment]
#! /usr/bin/env python
import pyowm
from wimd import wimd
import sys
import datetime

devkey = 'XXXXXXXXXXXXXXXX'
weatherKey = 'YYYYYYYYYYYYYYYY'
locations  = []
owm        = pyowm.OWM(weatherKey)

cities = [
{"_id":6454071,"name":"Grenoble","country":"FR","coord":{"lon":5.7266,"lat":45.187199}},
{"_id":3448439,"name":"Sao
Paulo","country":"BR","coord":{"lon":-46.636108,"lat":-23.547501}},
{"_id":3451190,"name":"Rio de
Janeiro","country":"BR","coord":{"lon":-43.2075,"lat":-22.902781}},
{"_id":5880054,"name":"Barrow","country":"US","coord":{"lon":-156.788727,"lat":71.290581}},
{"_id":3467865,"name":"Campinas","country":"BR","coord":{"lon":-47.060829,"lat":-22.90556}},
{"_id":292223,"name":"Dubai","country":"AE","coord":{"lon":55.304722,"lat":25.258169}},
{"_id":2013159,"name":"Yakutsk","country":"RU","coord":{"lon":129.733063,"lat":62.03389}},
{"_id":5178813,"name":"Bagdad","country":"US","coord":{"lon":-80.024223,"lat":41.952}},
{"_id":2449067,"name":"Timbuktu","country":"ML","coord":{"lon":-3.00742,"lat":16.773479}},
{"_id":2064144,"name":"Oodnadatta","country":"AU","coord":{"lon":135.466675,"lat":-27.549999}},
{"_id":2992908,"name":"Montbonnot-Saint-Martin","country":"FR","coord":{"lon":5.80353,"lat":45.222359}},
{"_id":3006131,"name":"La
Tronche","country":"FR","coord":{"lon":5.73645,"lat":45.204288}},
{"_id":2968815,"name":"Paris","country":"FR","coord":{"lon":2.3486,"lat":48.853401}},
{"_id":5128638,"name":"New
York","country":"US","coord":{"lon":-75.499901,"lat":43.000351}}
]


def add_sensor(id, name, timestamp, value, unit, description=''):
    rc = w.sensor_new(devkey, id, name, unit, description)
    if rc:
        rc = w.sensor_add_data(devkey, id ,timestamp, value)
        if rc == False:
            rc = -2
    else:
        rc = -1
    return rc

if __name__ == '__main__':
    w = wimd()
    for p in range(len(cities)):
        city = cities[p]
        print('Collecting weather data from ' + city['name'])
        try:
            observation = owm.weather_at_id(city['_id'])
            weather = observation.get_weather()
            t = weather.get_temperature('celsius')
            u = weather.get_humidity()
            p = '%Y-%m-%d %H:%M:%S'
            today = datetime.datetime.utcnow().strftime(p)
            print ('Temperature now in ' + city['name'] + ' is ' +
str(t['temp']) + ' with humidity of ' + str(u) + ' %')
            cid = city['name'] + '_' + city['country']
            name = city['name'] + ' - ' + city['country']
            rc = add_sensor(cid + '_C', name, today, t['temp'], 'C',
'Temperature')
            if rc > 0:
                rc = add_sensor(cid + '_RH', name, today, u, '%',
'Relative Humidity')
            if rc <= 0:
                print("Error creating sensor")
        except:
            print('********* Error reading data from ' + city['name'])

**Comment by csparpa** [comment]
Sorry, with that snippet I cannot reproduce the bug.

Can you then pls post here the exact call that gives the error and the full stack trace you see printed?

Thanks

**Comment by csparpa** [comment]
Anyway, now NaNs seems to be gone.

If I call in my browser:

    http://api.openweathermap.org/data/2.5/weather?id=5880054&appid=2de143494c0b295cca9337e1e96b00e0

where the ID is the one for Barrow, US then the response is:

```
{"coord":{"lon":-156.79,"lat":71.29},"weather":[{"id":800,"main":"Clear","description":"sky is clear","icon":"01d"}],"base":"cmc stations","main":{"temp":243.15,"pressure":1018,"humidity":82,"temp_min":243.15,"temp_max":243.15},"wind":{"speed":5.7,"deg":280},"clouds":{"all":1},"dt":1450947180,"sys":{"type":1,"id":26,"message":0.0099,"country":"US","sunrise":-7772456837,"sunset":-7772456837},"id":5880054,"name":"Barrow","cod":200}
```

Anyway, PyOWM should be able to detect and handle NaNs when the OWM API returns them (which, should anyway **never** happen in a perfect world :-p)

**Comment by Tangerino** [comment]
and now this...
Even in your example, sun rise/set and a very low values...
Barrow is a quit north place :D

Collecting weather data from Barrow
Traceback (most recent call last):
  File "/Users/carlos/Desktop/etl/weather.py", line 43, in <module>
    observation = owm.weather_at_id(city['_id'])
  File "/Library/Python/2.7/site-packages/pyowm/webapi25/owm25.py", line
200, in weather_at_id
    return self._parsers['observation'].parse_JSON(json_data)
  File
"/Library/Python/2.7/site-packages/pyowm/webapi25/observationparser.py",
line 60, in parse_JSON
    w = weather.weather_from_dictionary(d)
  File "/Library/Python/2.7/site-packages/pyowm/webapi25/weather.py", line
541, in weather_from_dictionary
    visibility_distance, dewpoint, humidex, heat_index)
  File "/Library/Python/2.7/site-packages/pyowm/webapi25/weather.py", line
67, in __init__
*    raise ValueError("'sunset_time' must be greatear than 0")*
ValueError: 'sunset_time' must be greatear than 0

**Comment by csparpa** [comment]
:) this is a different error of course.
Sunrise/sunset are Unix timestamps according to OWM API docs... Being
negative, it would mean that these times refer to lots of years ago!!
So I guess there's a flaw in the API here

Claudio Sparpaglione
http://csparpa.github.io
Il 24 dic 2015 18:51, "Carlos Tangerino" <notifications@github.com> ha
scritto:

> and now this...
> Even in your example, sun rise/set and a very low values...
> Barrow is a quit north place :D
>
> Collecting weather data from Barrow
> Traceback (most recent call last):
> File "/Users/carlos/Desktop/etl/weather.py", line 43, in <module>
> observation = owm.weather_at_id(city['_id'])
> File "/Library/Python/2.7/site-packages/pyowm/webapi25/owm25.py", line
> 200, in weather_at_id
> return self._parsers['observation'].parse_JSON(json_data)
> File
> "/Library/Python/2.7/site-packages/pyowm/webapi25/observationparser.py",
> line 60, in parse_JSON
> w = weather.weather_from_dictionary(d)
> File "/Library/Python/2.7/site-packages/pyowm/webapi25/weather.py", line
> 541, in weather_from_dictionary
> visibility_distance, dewpoint, humidex, heat_index)
> File "/Library/Python/2.7/site-packages/pyowm/webapi25/weather.py", line
> 67, in __init__
> * raise ValueError("'sunset_time' must be greatear than 0")*
> ValueError: 'sunset_time' must be greatear than 0
>
>
> On Thu, Dec 24, 2015 at 10:31 AM, Claudio Sparpaglione <

**Comment by csparpa** [comment]
As discussed in #94, I've opened a new feature request for release 3 (#97)
